# OpenPrintTag Schema Configuration
SCHEMA_REPO_URL="https://github.com/OpenPrintTag/openprinttag-architecture.git"
SCHEMA_COMMIT="bcf07d258fc5253c7e49417f7d7ee2acb26078c1"
SCHEMA_SPARSE_PATH="schema/generated/opt_db_schema"
SCHEMA_TARGET_DIR="./openprinttag"
