/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrintersRouteImport } from './routes/printers'
import { Route as PrintSheetTypesRouteImport } from './routes/print-sheet-types'
import { Route as EnumRouteImport } from './routes/enum'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnumIndexRouteImport } from './routes/enum.index'
import { Route as ContainersIndexRouteImport } from './routes/containers.index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as PrintersIdRouteImport } from './routes/printers.$id'
import { Route as PrintSheetTypesTypeIdRouteImport } from './routes/print-sheet-types.$typeId'
import { Route as PrintSheetTypesSlugRouteImport } from './routes/print-sheet-types.$slug'
import { Route as MaterialsMaterialIdRouteImport } from './routes/materials.$materialId'
import { Route as EnumTableRouteImport } from './routes/enum.$table'
import { Route as DevicesPrintersRouteImport } from './routes/devices.printers'
import { Route as DevicesAccessoriesRouteImport } from './routes/devices.accessories'
import { Route as ContainersIdRouteImport } from './routes/containers.$id'
import { Route as BrandsBrandIdRouteImport } from './routes/brands.$brandId'
import { Route as ApiSchemaRouteImport } from './routes/api/schema'
import { Route as ApiPrintSheetTypesRouteImport } from './routes/api/print-sheet-types'
import { Route as ApiPackagesRouteImport } from './routes/api/packages'
import { Route as ApiMaterialsRouteImport } from './routes/api/materials'
import { Route as ApiEnumRouteImport } from './routes/api/enum'
import { Route as ApiContainersRouteImport } from './routes/api/containers'
import { Route as ApiBrandsRouteImport } from './routes/api/brands'
import { Route as AccessoriesIdRouteImport } from './routes/accessories.$id'
import { Route as EnumTableIdRouteImport } from './routes/enum.$table.$id'
import { Route as DevicesPrintersPrinterIdRouteImport } from './routes/devices.printers.$printerId'
import { Route as DevicesPrintersIdRouteImport } from './routes/devices.printers.$id'
import { Route as DevicesAccessoriesIdRouteImport } from './routes/devices.accessories.$id'
import { Route as ApiPrintSheetTypesTypeIdRouteImport } from './routes/api/print-sheet-types.$typeId'
import { Route as ApiPrintSheetTypesSlugRouteImport } from './routes/api/print-sheet-types.$slug'
import { Route as ApiMaterialsMaterialIdRouteImport } from './routes/api/materials.$materialId'
import { Route as ApiEnumTableRouteImport } from './routes/api/enum.$table'
import { Route as ApiDevicesPrintersRouteImport } from './routes/api/devices.printers'
import { Route as ApiDevicesAccessoriesRouteImport } from './routes/api/devices.accessories'
import { Route as ApiContainersIdRouteImport } from './routes/api/containers.$id'
import { Route as ApiContainersContainerIdRouteImport } from './routes/api/containers.$containerId'
import { Route as ApiBrandsBasicRouteImport } from './routes/api/brands.basic'
import { Route as ApiBrandsBrandIdRouteImport } from './routes/api/brands.$brandId'
import { Route as BrandsBrandIdMaterialsMaterialIdRouteImport } from './routes/brands.$brandId.materials.$materialId'
import { Route as ApiEnumTableIdRouteImport } from './routes/api/enum.$table.$id'
import { Route as ApiDevicesPrintersPrinterIdRouteImport } from './routes/api/devices.printers.$printerId'
import { Route as ApiDevicesPrintersIdRouteImport } from './routes/api/devices.printers.$id'
import { Route as ApiDevicesAccessoriesIdRouteImport } from './routes/api/devices.accessories.$id'
import { Route as ApiDevicesAccessoriesAccessoryIdRouteImport } from './routes/api/devices.accessories.$accessoryId'
import { Route as ApiBrandsBrandIdPackagesRouteImport } from './routes/api/brands.$brandId.packages'
import { Route as ApiBrandsBrandIdMaterialsRouteImport } from './routes/api/brands.$brandId.materials'
import { Route as ApiBrandsBrandIdCountsRouteImport } from './routes/api/brands.$brandId.counts'
import { Route as ApiBrandsBrandIdPackagesNewRouteImport } from './routes/api/brands.$brandId.packages.new'
import { Route as ApiBrandsBrandIdPackagesPackageIdRouteImport } from './routes/api/brands.$brandId.packages.$packageId'
import { Route as ApiBrandsBrandIdMaterialsNewRouteImport } from './routes/api/brands.$brandId.materials.new'
import { Route as ApiBrandsBrandIdMaterialsMaterialIdRouteImport } from './routes/api/brands.$brandId.materials.$materialId'

const PrintersRoute = PrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintSheetTypesRoute = PrintSheetTypesRouteImport.update({
  id: '/print-sheet-types',
  path: '/print-sheet-types',
  getParentRoute: () => rootRouteImport,
} as any)
const EnumRoute = EnumRouteImport.update({
  id: '/enum',
  path: '/enum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnumIndexRoute = EnumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnumRoute,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContainersRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsRoute,
} as any)
const PrintersIdRoute = PrintersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PrintersRoute,
} as any)
const PrintSheetTypesTypeIdRoute = PrintSheetTypesTypeIdRouteImport.update({
  id: '/$typeId',
  path: '/$typeId',
  getParentRoute: () => PrintSheetTypesRoute,
} as any)
const PrintSheetTypesSlugRoute = PrintSheetTypesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PrintSheetTypesRoute,
} as any)
const MaterialsMaterialIdRoute = MaterialsMaterialIdRouteImport.update({
  id: '/materials/$materialId',
  path: '/materials/$materialId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnumTableRoute = EnumTableRouteImport.update({
  id: '/$table',
  path: '/$table',
  getParentRoute: () => EnumRoute,
} as any)
const DevicesPrintersRoute = DevicesPrintersRouteImport.update({
  id: '/devices/printers',
  path: '/devices/printers',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesAccessoriesRoute = DevicesAccessoriesRouteImport.update({
  id: '/devices/accessories',
  path: '/devices/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIdRoute = ContainersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContainersRoute,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/$brandId',
  path: '/$brandId',
  getParentRoute: () => BrandsRoute,
} as any)
const ApiSchemaRoute = ApiSchemaRouteImport.update({
  id: '/api/schema',
  path: '/api/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrintSheetTypesRoute = ApiPrintSheetTypesRouteImport.update({
  id: '/api/print-sheet-types',
  path: '/api/print-sheet-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPackagesRoute = ApiPackagesRouteImport.update({
  id: '/api/packages',
  path: '/api/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaterialsRoute = ApiMaterialsRouteImport.update({
  id: '/api/materials',
  path: '/api/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnumRoute = ApiEnumRouteImport.update({
  id: '/api/enum',
  path: '/api/enum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContainersRoute = ApiContainersRouteImport.update({
  id: '/api/containers',
  path: '/api/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandsRoute = ApiBrandsRouteImport.update({
  id: '/api/brands',
  path: '/api/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesIdRoute = AccessoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccessoriesRoute,
} as any)
const EnumTableIdRoute = EnumTableIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EnumTableRoute,
} as any)
const DevicesPrintersPrinterIdRoute =
  DevicesPrintersPrinterIdRouteImport.update({
    id: '/$printerId',
    path: '/$printerId',
    getParentRoute: () => DevicesPrintersRoute,
  } as any)
const DevicesPrintersIdRoute = DevicesPrintersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DevicesPrintersRoute,
} as any)
const DevicesAccessoriesIdRoute = DevicesAccessoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DevicesAccessoriesRoute,
} as any)
const ApiPrintSheetTypesTypeIdRoute =
  ApiPrintSheetTypesTypeIdRouteImport.update({
    id: '/$typeId',
    path: '/$typeId',
    getParentRoute: () => ApiPrintSheetTypesRoute,
  } as any)
const ApiPrintSheetTypesSlugRoute = ApiPrintSheetTypesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPrintSheetTypesRoute,
} as any)
const ApiMaterialsMaterialIdRoute = ApiMaterialsMaterialIdRouteImport.update({
  id: '/$materialId',
  path: '/$materialId',
  getParentRoute: () => ApiMaterialsRoute,
} as any)
const ApiEnumTableRoute = ApiEnumTableRouteImport.update({
  id: '/$table',
  path: '/$table',
  getParentRoute: () => ApiEnumRoute,
} as any)
const ApiDevicesPrintersRoute = ApiDevicesPrintersRouteImport.update({
  id: '/api/devices/printers',
  path: '/api/devices/printers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesAccessoriesRoute = ApiDevicesAccessoriesRouteImport.update({
  id: '/api/devices/accessories',
  path: '/api/devices/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContainersIdRoute = ApiContainersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiContainersRoute,
} as any)
const ApiContainersContainerIdRoute =
  ApiContainersContainerIdRouteImport.update({
    id: '/$containerId',
    path: '/$containerId',
    getParentRoute: () => ApiContainersRoute,
  } as any)
const ApiBrandsBasicRoute = ApiBrandsBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => ApiBrandsRoute,
} as any)
const ApiBrandsBrandIdRoute = ApiBrandsBrandIdRouteImport.update({
  id: '/$brandId',
  path: '/$brandId',
  getParentRoute: () => ApiBrandsRoute,
} as any)
const BrandsBrandIdMaterialsMaterialIdRoute =
  BrandsBrandIdMaterialsMaterialIdRouteImport.update({
    id: '/materials/$materialId',
    path: '/materials/$materialId',
    getParentRoute: () => BrandsBrandIdRoute,
  } as any)
const ApiEnumTableIdRoute = ApiEnumTableIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEnumTableRoute,
} as any)
const ApiDevicesPrintersPrinterIdRoute =
  ApiDevicesPrintersPrinterIdRouteImport.update({
    id: '/$printerId',
    path: '/$printerId',
    getParentRoute: () => ApiDevicesPrintersRoute,
  } as any)
const ApiDevicesPrintersIdRoute = ApiDevicesPrintersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDevicesPrintersRoute,
} as any)
const ApiDevicesAccessoriesIdRoute = ApiDevicesAccessoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDevicesAccessoriesRoute,
} as any)
const ApiDevicesAccessoriesAccessoryIdRoute =
  ApiDevicesAccessoriesAccessoryIdRouteImport.update({
    id: '/$accessoryId',
    path: '/$accessoryId',
    getParentRoute: () => ApiDevicesAccessoriesRoute,
  } as any)
const ApiBrandsBrandIdPackagesRoute =
  ApiBrandsBrandIdPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => ApiBrandsBrandIdRoute,
  } as any)
const ApiBrandsBrandIdMaterialsRoute =
  ApiBrandsBrandIdMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => ApiBrandsBrandIdRoute,
  } as any)
const ApiBrandsBrandIdCountsRoute = ApiBrandsBrandIdCountsRouteImport.update({
  id: '/counts',
  path: '/counts',
  getParentRoute: () => ApiBrandsBrandIdRoute,
} as any)
const ApiBrandsBrandIdPackagesNewRoute =
  ApiBrandsBrandIdPackagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ApiBrandsBrandIdPackagesRoute,
  } as any)
const ApiBrandsBrandIdPackagesPackageIdRoute =
  ApiBrandsBrandIdPackagesPackageIdRouteImport.update({
    id: '/$packageId',
    path: '/$packageId',
    getParentRoute: () => ApiBrandsBrandIdPackagesRoute,
  } as any)
const ApiBrandsBrandIdMaterialsNewRoute =
  ApiBrandsBrandIdMaterialsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ApiBrandsBrandIdMaterialsRoute,
  } as any)
const ApiBrandsBrandIdMaterialsMaterialIdRoute =
  ApiBrandsBrandIdMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => ApiBrandsBrandIdMaterialsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/brands': typeof BrandsRouteWithChildren
  '/containers': typeof ContainersRouteWithChildren
  '/enum': typeof EnumRouteWithChildren
  '/print-sheet-types': typeof PrintSheetTypesRouteWithChildren
  '/printers': typeof PrintersRouteWithChildren
  '/accessories/$id': typeof AccessoriesIdRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/api/containers': typeof ApiContainersRouteWithChildren
  '/api/enum': typeof ApiEnumRouteWithChildren
  '/api/materials': typeof ApiMaterialsRouteWithChildren
  '/api/packages': typeof ApiPackagesRoute
  '/api/print-sheet-types': typeof ApiPrintSheetTypesRouteWithChildren
  '/api/schema': typeof ApiSchemaRoute
  '/brands/$brandId': typeof BrandsBrandIdRouteWithChildren
  '/containers/$id': typeof ContainersIdRoute
  '/devices/accessories': typeof DevicesAccessoriesRouteWithChildren
  '/devices/printers': typeof DevicesPrintersRouteWithChildren
  '/enum/$table': typeof EnumTableRouteWithChildren
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/print-sheet-types/$slug': typeof PrintSheetTypesSlugRoute
  '/print-sheet-types/$typeId': typeof PrintSheetTypesTypeIdRoute
  '/printers/$id': typeof PrintersIdRoute
  '/brands/': typeof BrandsIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/enum/': typeof EnumIndexRoute
  '/api/brands/$brandId': typeof ApiBrandsBrandIdRouteWithChildren
  '/api/brands/basic': typeof ApiBrandsBasicRoute
  '/api/containers/$containerId': typeof ApiContainersContainerIdRoute
  '/api/containers/$id': typeof ApiContainersIdRoute
  '/api/devices/accessories': typeof ApiDevicesAccessoriesRouteWithChildren
  '/api/devices/printers': typeof ApiDevicesPrintersRouteWithChildren
  '/api/enum/$table': typeof ApiEnumTableRouteWithChildren
  '/api/materials/$materialId': typeof ApiMaterialsMaterialIdRoute
  '/api/print-sheet-types/$slug': typeof ApiPrintSheetTypesSlugRoute
  '/api/print-sheet-types/$typeId': typeof ApiPrintSheetTypesTypeIdRoute
  '/devices/accessories/$id': typeof DevicesAccessoriesIdRoute
  '/devices/printers/$id': typeof DevicesPrintersIdRoute
  '/devices/printers/$printerId': typeof DevicesPrintersPrinterIdRoute
  '/enum/$table/$id': typeof EnumTableIdRoute
  '/api/brands/$brandId/counts': typeof ApiBrandsBrandIdCountsRoute
  '/api/brands/$brandId/materials': typeof ApiBrandsBrandIdMaterialsRouteWithChildren
  '/api/brands/$brandId/packages': typeof ApiBrandsBrandIdPackagesRouteWithChildren
  '/api/devices/accessories/$accessoryId': typeof ApiDevicesAccessoriesAccessoryIdRoute
  '/api/devices/accessories/$id': typeof ApiDevicesAccessoriesIdRoute
  '/api/devices/printers/$id': typeof ApiDevicesPrintersIdRoute
  '/api/devices/printers/$printerId': typeof ApiDevicesPrintersPrinterIdRoute
  '/api/enum/$table/$id': typeof ApiEnumTableIdRoute
  '/brands/$brandId/materials/$materialId': typeof BrandsBrandIdMaterialsMaterialIdRoute
  '/api/brands/$brandId/materials/$materialId': typeof ApiBrandsBrandIdMaterialsMaterialIdRoute
  '/api/brands/$brandId/materials/new': typeof ApiBrandsBrandIdMaterialsNewRoute
  '/api/brands/$brandId/packages/$packageId': typeof ApiBrandsBrandIdPackagesPackageIdRoute
  '/api/brands/$brandId/packages/new': typeof ApiBrandsBrandIdPackagesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/print-sheet-types': typeof PrintSheetTypesRouteWithChildren
  '/printers': typeof PrintersRouteWithChildren
  '/accessories/$id': typeof AccessoriesIdRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/api/containers': typeof ApiContainersRouteWithChildren
  '/api/enum': typeof ApiEnumRouteWithChildren
  '/api/materials': typeof ApiMaterialsRouteWithChildren
  '/api/packages': typeof ApiPackagesRoute
  '/api/print-sheet-types': typeof ApiPrintSheetTypesRouteWithChildren
  '/api/schema': typeof ApiSchemaRoute
  '/brands/$brandId': typeof BrandsBrandIdRouteWithChildren
  '/containers/$id': typeof ContainersIdRoute
  '/devices/accessories': typeof DevicesAccessoriesRouteWithChildren
  '/devices/printers': typeof DevicesPrintersRouteWithChildren
  '/enum/$table': typeof EnumTableRouteWithChildren
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/print-sheet-types/$slug': typeof PrintSheetTypesSlugRoute
  '/print-sheet-types/$typeId': typeof PrintSheetTypesTypeIdRoute
  '/printers/$id': typeof PrintersIdRoute
  '/brands': typeof BrandsIndexRoute
  '/containers': typeof ContainersIndexRoute
  '/enum': typeof EnumIndexRoute
  '/api/brands/$brandId': typeof ApiBrandsBrandIdRouteWithChildren
  '/api/brands/basic': typeof ApiBrandsBasicRoute
  '/api/containers/$containerId': typeof ApiContainersContainerIdRoute
  '/api/containers/$id': typeof ApiContainersIdRoute
  '/api/devices/accessories': typeof ApiDevicesAccessoriesRouteWithChildren
  '/api/devices/printers': typeof ApiDevicesPrintersRouteWithChildren
  '/api/enum/$table': typeof ApiEnumTableRouteWithChildren
  '/api/materials/$materialId': typeof ApiMaterialsMaterialIdRoute
  '/api/print-sheet-types/$slug': typeof ApiPrintSheetTypesSlugRoute
  '/api/print-sheet-types/$typeId': typeof ApiPrintSheetTypesTypeIdRoute
  '/devices/accessories/$id': typeof DevicesAccessoriesIdRoute
  '/devices/printers/$id': typeof DevicesPrintersIdRoute
  '/devices/printers/$printerId': typeof DevicesPrintersPrinterIdRoute
  '/enum/$table/$id': typeof EnumTableIdRoute
  '/api/brands/$brandId/counts': typeof ApiBrandsBrandIdCountsRoute
  '/api/brands/$brandId/materials': typeof ApiBrandsBrandIdMaterialsRouteWithChildren
  '/api/brands/$brandId/packages': typeof ApiBrandsBrandIdPackagesRouteWithChildren
  '/api/devices/accessories/$accessoryId': typeof ApiDevicesAccessoriesAccessoryIdRoute
  '/api/devices/accessories/$id': typeof ApiDevicesAccessoriesIdRoute
  '/api/devices/printers/$id': typeof ApiDevicesPrintersIdRoute
  '/api/devices/printers/$printerId': typeof ApiDevicesPrintersPrinterIdRoute
  '/api/enum/$table/$id': typeof ApiEnumTableIdRoute
  '/brands/$brandId/materials/$materialId': typeof BrandsBrandIdMaterialsMaterialIdRoute
  '/api/brands/$brandId/materials/$materialId': typeof ApiBrandsBrandIdMaterialsMaterialIdRoute
  '/api/brands/$brandId/materials/new': typeof ApiBrandsBrandIdMaterialsNewRoute
  '/api/brands/$brandId/packages/$packageId': typeof ApiBrandsBrandIdPackagesPackageIdRoute
  '/api/brands/$brandId/packages/new': typeof ApiBrandsBrandIdPackagesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/brands': typeof BrandsRouteWithChildren
  '/containers': typeof ContainersRouteWithChildren
  '/enum': typeof EnumRouteWithChildren
  '/print-sheet-types': typeof PrintSheetTypesRouteWithChildren
  '/printers': typeof PrintersRouteWithChildren
  '/accessories/$id': typeof AccessoriesIdRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/api/containers': typeof ApiContainersRouteWithChildren
  '/api/enum': typeof ApiEnumRouteWithChildren
  '/api/materials': typeof ApiMaterialsRouteWithChildren
  '/api/packages': typeof ApiPackagesRoute
  '/api/print-sheet-types': typeof ApiPrintSheetTypesRouteWithChildren
  '/api/schema': typeof ApiSchemaRoute
  '/brands/$brandId': typeof BrandsBrandIdRouteWithChildren
  '/containers/$id': typeof ContainersIdRoute
  '/devices/accessories': typeof DevicesAccessoriesRouteWithChildren
  '/devices/printers': typeof DevicesPrintersRouteWithChildren
  '/enum/$table': typeof EnumTableRouteWithChildren
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/print-sheet-types/$slug': typeof PrintSheetTypesSlugRoute
  '/print-sheet-types/$typeId': typeof PrintSheetTypesTypeIdRoute
  '/printers/$id': typeof PrintersIdRoute
  '/brands/': typeof BrandsIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/enum/': typeof EnumIndexRoute
  '/api/brands/$brandId': typeof ApiBrandsBrandIdRouteWithChildren
  '/api/brands/basic': typeof ApiBrandsBasicRoute
  '/api/containers/$containerId': typeof ApiContainersContainerIdRoute
  '/api/containers/$id': typeof ApiContainersIdRoute
  '/api/devices/accessories': typeof ApiDevicesAccessoriesRouteWithChildren
  '/api/devices/printers': typeof ApiDevicesPrintersRouteWithChildren
  '/api/enum/$table': typeof ApiEnumTableRouteWithChildren
  '/api/materials/$materialId': typeof ApiMaterialsMaterialIdRoute
  '/api/print-sheet-types/$slug': typeof ApiPrintSheetTypesSlugRoute
  '/api/print-sheet-types/$typeId': typeof ApiPrintSheetTypesTypeIdRoute
  '/devices/accessories/$id': typeof DevicesAccessoriesIdRoute
  '/devices/printers/$id': typeof DevicesPrintersIdRoute
  '/devices/printers/$printerId': typeof DevicesPrintersPrinterIdRoute
  '/enum/$table/$id': typeof EnumTableIdRoute
  '/api/brands/$brandId/counts': typeof ApiBrandsBrandIdCountsRoute
  '/api/brands/$brandId/materials': typeof ApiBrandsBrandIdMaterialsRouteWithChildren
  '/api/brands/$brandId/packages': typeof ApiBrandsBrandIdPackagesRouteWithChildren
  '/api/devices/accessories/$accessoryId': typeof ApiDevicesAccessoriesAccessoryIdRoute
  '/api/devices/accessories/$id': typeof ApiDevicesAccessoriesIdRoute
  '/api/devices/printers/$id': typeof ApiDevicesPrintersIdRoute
  '/api/devices/printers/$printerId': typeof ApiDevicesPrintersPrinterIdRoute
  '/api/enum/$table/$id': typeof ApiEnumTableIdRoute
  '/brands/$brandId/materials/$materialId': typeof BrandsBrandIdMaterialsMaterialIdRoute
  '/api/brands/$brandId/materials/$materialId': typeof ApiBrandsBrandIdMaterialsMaterialIdRoute
  '/api/brands/$brandId/materials/new': typeof ApiBrandsBrandIdMaterialsNewRoute
  '/api/brands/$brandId/packages/$packageId': typeof ApiBrandsBrandIdPackagesPackageIdRoute
  '/api/brands/$brandId/packages/new': typeof ApiBrandsBrandIdPackagesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/brands'
    | '/containers'
    | '/enum'
    | '/print-sheet-types'
    | '/printers'
    | '/accessories/$id'
    | '/api/brands'
    | '/api/containers'
    | '/api/enum'
    | '/api/materials'
    | '/api/packages'
    | '/api/print-sheet-types'
    | '/api/schema'
    | '/brands/$brandId'
    | '/containers/$id'
    | '/devices/accessories'
    | '/devices/printers'
    | '/enum/$table'
    | '/materials/$materialId'
    | '/print-sheet-types/$slug'
    | '/print-sheet-types/$typeId'
    | '/printers/$id'
    | '/brands/'
    | '/containers/'
    | '/enum/'
    | '/api/brands/$brandId'
    | '/api/brands/basic'
    | '/api/containers/$containerId'
    | '/api/containers/$id'
    | '/api/devices/accessories'
    | '/api/devices/printers'
    | '/api/enum/$table'
    | '/api/materials/$materialId'
    | '/api/print-sheet-types/$slug'
    | '/api/print-sheet-types/$typeId'
    | '/devices/accessories/$id'
    | '/devices/printers/$id'
    | '/devices/printers/$printerId'
    | '/enum/$table/$id'
    | '/api/brands/$brandId/counts'
    | '/api/brands/$brandId/materials'
    | '/api/brands/$brandId/packages'
    | '/api/devices/accessories/$accessoryId'
    | '/api/devices/accessories/$id'
    | '/api/devices/printers/$id'
    | '/api/devices/printers/$printerId'
    | '/api/enum/$table/$id'
    | '/brands/$brandId/materials/$materialId'
    | '/api/brands/$brandId/materials/$materialId'
    | '/api/brands/$brandId/materials/new'
    | '/api/brands/$brandId/packages/$packageId'
    | '/api/brands/$brandId/packages/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/print-sheet-types'
    | '/printers'
    | '/accessories/$id'
    | '/api/brands'
    | '/api/containers'
    | '/api/enum'
    | '/api/materials'
    | '/api/packages'
    | '/api/print-sheet-types'
    | '/api/schema'
    | '/brands/$brandId'
    | '/containers/$id'
    | '/devices/accessories'
    | '/devices/printers'
    | '/enum/$table'
    | '/materials/$materialId'
    | '/print-sheet-types/$slug'
    | '/print-sheet-types/$typeId'
    | '/printers/$id'
    | '/brands'
    | '/containers'
    | '/enum'
    | '/api/brands/$brandId'
    | '/api/brands/basic'
    | '/api/containers/$containerId'
    | '/api/containers/$id'
    | '/api/devices/accessories'
    | '/api/devices/printers'
    | '/api/enum/$table'
    | '/api/materials/$materialId'
    | '/api/print-sheet-types/$slug'
    | '/api/print-sheet-types/$typeId'
    | '/devices/accessories/$id'
    | '/devices/printers/$id'
    | '/devices/printers/$printerId'
    | '/enum/$table/$id'
    | '/api/brands/$brandId/counts'
    | '/api/brands/$brandId/materials'
    | '/api/brands/$brandId/packages'
    | '/api/devices/accessories/$accessoryId'
    | '/api/devices/accessories/$id'
    | '/api/devices/printers/$id'
    | '/api/devices/printers/$printerId'
    | '/api/enum/$table/$id'
    | '/brands/$brandId/materials/$materialId'
    | '/api/brands/$brandId/materials/$materialId'
    | '/api/brands/$brandId/materials/new'
    | '/api/brands/$brandId/packages/$packageId'
    | '/api/brands/$brandId/packages/new'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/brands'
    | '/containers'
    | '/enum'
    | '/print-sheet-types'
    | '/printers'
    | '/accessories/$id'
    | '/api/brands'
    | '/api/containers'
    | '/api/enum'
    | '/api/materials'
    | '/api/packages'
    | '/api/print-sheet-types'
    | '/api/schema'
    | '/brands/$brandId'
    | '/containers/$id'
    | '/devices/accessories'
    | '/devices/printers'
    | '/enum/$table'
    | '/materials/$materialId'
    | '/print-sheet-types/$slug'
    | '/print-sheet-types/$typeId'
    | '/printers/$id'
    | '/brands/'
    | '/containers/'
    | '/enum/'
    | '/api/brands/$brandId'
    | '/api/brands/basic'
    | '/api/containers/$containerId'
    | '/api/containers/$id'
    | '/api/devices/accessories'
    | '/api/devices/printers'
    | '/api/enum/$table'
    | '/api/materials/$materialId'
    | '/api/print-sheet-types/$slug'
    | '/api/print-sheet-types/$typeId'
    | '/devices/accessories/$id'
    | '/devices/printers/$id'
    | '/devices/printers/$printerId'
    | '/enum/$table/$id'
    | '/api/brands/$brandId/counts'
    | '/api/brands/$brandId/materials'
    | '/api/brands/$brandId/packages'
    | '/api/devices/accessories/$accessoryId'
    | '/api/devices/accessories/$id'
    | '/api/devices/printers/$id'
    | '/api/devices/printers/$printerId'
    | '/api/enum/$table/$id'
    | '/brands/$brandId/materials/$materialId'
    | '/api/brands/$brandId/materials/$materialId'
    | '/api/brands/$brandId/materials/new'
    | '/api/brands/$brandId/packages/$packageId'
    | '/api/brands/$brandId/packages/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRouteWithChildren
  BrandsRoute: typeof BrandsRouteWithChildren
  ContainersRoute: typeof ContainersRouteWithChildren
  EnumRoute: typeof EnumRouteWithChildren
  PrintSheetTypesRoute: typeof PrintSheetTypesRouteWithChildren
  PrintersRoute: typeof PrintersRouteWithChildren
  ApiBrandsRoute: typeof ApiBrandsRouteWithChildren
  ApiContainersRoute: typeof ApiContainersRouteWithChildren
  ApiEnumRoute: typeof ApiEnumRouteWithChildren
  ApiMaterialsRoute: typeof ApiMaterialsRouteWithChildren
  ApiPackagesRoute: typeof ApiPackagesRoute
  ApiPrintSheetTypesRoute: typeof ApiPrintSheetTypesRouteWithChildren
  ApiSchemaRoute: typeof ApiSchemaRoute
  DevicesAccessoriesRoute: typeof DevicesAccessoriesRouteWithChildren
  DevicesPrintersRoute: typeof DevicesPrintersRouteWithChildren
  MaterialsMaterialIdRoute: typeof MaterialsMaterialIdRoute
  ApiDevicesAccessoriesRoute: typeof ApiDevicesAccessoriesRouteWithChildren
  ApiDevicesPrintersRoute: typeof ApiDevicesPrintersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/printers': {
      id: '/printers'
      path: '/printers'
      fullPath: '/printers'
      preLoaderRoute: typeof PrintersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-sheet-types': {
      id: '/print-sheet-types'
      path: '/print-sheet-types'
      fullPath: '/print-sheet-types'
      preLoaderRoute: typeof PrintSheetTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enum': {
      id: '/enum'
      path: '/enum'
      fullPath: '/enum'
      preLoaderRoute: typeof EnumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enum/': {
      id: '/enum/'
      path: '/'
      fullPath: '/enum/'
      preLoaderRoute: typeof EnumIndexRouteImport
      parentRoute: typeof EnumRoute
    }
    '/containers/': {
      id: '/containers/'
      path: '/'
      fullPath: '/containers/'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof ContainersRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/printers/$id': {
      id: '/printers/$id'
      path: '/$id'
      fullPath: '/printers/$id'
      preLoaderRoute: typeof PrintersIdRouteImport
      parentRoute: typeof PrintersRoute
    }
    '/print-sheet-types/$typeId': {
      id: '/print-sheet-types/$typeId'
      path: '/$typeId'
      fullPath: '/print-sheet-types/$typeId'
      preLoaderRoute: typeof PrintSheetTypesTypeIdRouteImport
      parentRoute: typeof PrintSheetTypesRoute
    }
    '/print-sheet-types/$slug': {
      id: '/print-sheet-types/$slug'
      path: '/$slug'
      fullPath: '/print-sheet-types/$slug'
      preLoaderRoute: typeof PrintSheetTypesSlugRouteImport
      parentRoute: typeof PrintSheetTypesRoute
    }
    '/materials/$materialId': {
      id: '/materials/$materialId'
      path: '/materials/$materialId'
      fullPath: '/materials/$materialId'
      preLoaderRoute: typeof MaterialsMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enum/$table': {
      id: '/enum/$table'
      path: '/$table'
      fullPath: '/enum/$table'
      preLoaderRoute: typeof EnumTableRouteImport
      parentRoute: typeof EnumRoute
    }
    '/devices/printers': {
      id: '/devices/printers'
      path: '/devices/printers'
      fullPath: '/devices/printers'
      preLoaderRoute: typeof DevicesPrintersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/accessories': {
      id: '/devices/accessories'
      path: '/devices/accessories'
      fullPath: '/devices/accessories'
      preLoaderRoute: typeof DevicesAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$id': {
      id: '/containers/$id'
      path: '/$id'
      fullPath: '/containers/$id'
      preLoaderRoute: typeof ContainersIdRouteImport
      parentRoute: typeof ContainersRoute
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/api/schema': {
      id: '/api/schema'
      path: '/api/schema'
      fullPath: '/api/schema'
      preLoaderRoute: typeof ApiSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/print-sheet-types': {
      id: '/api/print-sheet-types'
      path: '/api/print-sheet-types'
      fullPath: '/api/print-sheet-types'
      preLoaderRoute: typeof ApiPrintSheetTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packages': {
      id: '/api/packages'
      path: '/api/packages'
      fullPath: '/api/packages'
      preLoaderRoute: typeof ApiPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/materials': {
      id: '/api/materials'
      path: '/api/materials'
      fullPath: '/api/materials'
      preLoaderRoute: typeof ApiMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enum': {
      id: '/api/enum'
      path: '/api/enum'
      fullPath: '/api/enum'
      preLoaderRoute: typeof ApiEnumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/containers': {
      id: '/api/containers'
      path: '/api/containers'
      fullPath: '/api/containers'
      preLoaderRoute: typeof ApiContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brands': {
      id: '/api/brands'
      path: '/api/brands'
      fullPath: '/api/brands'
      preLoaderRoute: typeof ApiBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/$id': {
      id: '/accessories/$id'
      path: '/$id'
      fullPath: '/accessories/$id'
      preLoaderRoute: typeof AccessoriesIdRouteImport
      parentRoute: typeof AccessoriesRoute
    }
    '/enum/$table/$id': {
      id: '/enum/$table/$id'
      path: '/$id'
      fullPath: '/enum/$table/$id'
      preLoaderRoute: typeof EnumTableIdRouteImport
      parentRoute: typeof EnumTableRoute
    }
    '/devices/printers/$printerId': {
      id: '/devices/printers/$printerId'
      path: '/$printerId'
      fullPath: '/devices/printers/$printerId'
      preLoaderRoute: typeof DevicesPrintersPrinterIdRouteImport
      parentRoute: typeof DevicesPrintersRoute
    }
    '/devices/printers/$id': {
      id: '/devices/printers/$id'
      path: '/$id'
      fullPath: '/devices/printers/$id'
      preLoaderRoute: typeof DevicesPrintersIdRouteImport
      parentRoute: typeof DevicesPrintersRoute
    }
    '/devices/accessories/$id': {
      id: '/devices/accessories/$id'
      path: '/$id'
      fullPath: '/devices/accessories/$id'
      preLoaderRoute: typeof DevicesAccessoriesIdRouteImport
      parentRoute: typeof DevicesAccessoriesRoute
    }
    '/api/print-sheet-types/$typeId': {
      id: '/api/print-sheet-types/$typeId'
      path: '/$typeId'
      fullPath: '/api/print-sheet-types/$typeId'
      preLoaderRoute: typeof ApiPrintSheetTypesTypeIdRouteImport
      parentRoute: typeof ApiPrintSheetTypesRoute
    }
    '/api/print-sheet-types/$slug': {
      id: '/api/print-sheet-types/$slug'
      path: '/$slug'
      fullPath: '/api/print-sheet-types/$slug'
      preLoaderRoute: typeof ApiPrintSheetTypesSlugRouteImport
      parentRoute: typeof ApiPrintSheetTypesRoute
    }
    '/api/materials/$materialId': {
      id: '/api/materials/$materialId'
      path: '/$materialId'
      fullPath: '/api/materials/$materialId'
      preLoaderRoute: typeof ApiMaterialsMaterialIdRouteImport
      parentRoute: typeof ApiMaterialsRoute
    }
    '/api/enum/$table': {
      id: '/api/enum/$table'
      path: '/$table'
      fullPath: '/api/enum/$table'
      preLoaderRoute: typeof ApiEnumTableRouteImport
      parentRoute: typeof ApiEnumRoute
    }
    '/api/devices/printers': {
      id: '/api/devices/printers'
      path: '/api/devices/printers'
      fullPath: '/api/devices/printers'
      preLoaderRoute: typeof ApiDevicesPrintersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/accessories': {
      id: '/api/devices/accessories'
      path: '/api/devices/accessories'
      fullPath: '/api/devices/accessories'
      preLoaderRoute: typeof ApiDevicesAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/containers/$id': {
      id: '/api/containers/$id'
      path: '/$id'
      fullPath: '/api/containers/$id'
      preLoaderRoute: typeof ApiContainersIdRouteImport
      parentRoute: typeof ApiContainersRoute
    }
    '/api/containers/$containerId': {
      id: '/api/containers/$containerId'
      path: '/$containerId'
      fullPath: '/api/containers/$containerId'
      preLoaderRoute: typeof ApiContainersContainerIdRouteImport
      parentRoute: typeof ApiContainersRoute
    }
    '/api/brands/basic': {
      id: '/api/brands/basic'
      path: '/basic'
      fullPath: '/api/brands/basic'
      preLoaderRoute: typeof ApiBrandsBasicRouteImport
      parentRoute: typeof ApiBrandsRoute
    }
    '/api/brands/$brandId': {
      id: '/api/brands/$brandId'
      path: '/$brandId'
      fullPath: '/api/brands/$brandId'
      preLoaderRoute: typeof ApiBrandsBrandIdRouteImport
      parentRoute: typeof ApiBrandsRoute
    }
    '/brands/$brandId/materials/$materialId': {
      id: '/brands/$brandId/materials/$materialId'
      path: '/materials/$materialId'
      fullPath: '/brands/$brandId/materials/$materialId'
      preLoaderRoute: typeof BrandsBrandIdMaterialsMaterialIdRouteImport
      parentRoute: typeof BrandsBrandIdRoute
    }
    '/api/enum/$table/$id': {
      id: '/api/enum/$table/$id'
      path: '/$id'
      fullPath: '/api/enum/$table/$id'
      preLoaderRoute: typeof ApiEnumTableIdRouteImport
      parentRoute: typeof ApiEnumTableRoute
    }
    '/api/devices/printers/$printerId': {
      id: '/api/devices/printers/$printerId'
      path: '/$printerId'
      fullPath: '/api/devices/printers/$printerId'
      preLoaderRoute: typeof ApiDevicesPrintersPrinterIdRouteImport
      parentRoute: typeof ApiDevicesPrintersRoute
    }
    '/api/devices/printers/$id': {
      id: '/api/devices/printers/$id'
      path: '/$id'
      fullPath: '/api/devices/printers/$id'
      preLoaderRoute: typeof ApiDevicesPrintersIdRouteImport
      parentRoute: typeof ApiDevicesPrintersRoute
    }
    '/api/devices/accessories/$id': {
      id: '/api/devices/accessories/$id'
      path: '/$id'
      fullPath: '/api/devices/accessories/$id'
      preLoaderRoute: typeof ApiDevicesAccessoriesIdRouteImport
      parentRoute: typeof ApiDevicesAccessoriesRoute
    }
    '/api/devices/accessories/$accessoryId': {
      id: '/api/devices/accessories/$accessoryId'
      path: '/$accessoryId'
      fullPath: '/api/devices/accessories/$accessoryId'
      preLoaderRoute: typeof ApiDevicesAccessoriesAccessoryIdRouteImport
      parentRoute: typeof ApiDevicesAccessoriesRoute
    }
    '/api/brands/$brandId/packages': {
      id: '/api/brands/$brandId/packages'
      path: '/packages'
      fullPath: '/api/brands/$brandId/packages'
      preLoaderRoute: typeof ApiBrandsBrandIdPackagesRouteImport
      parentRoute: typeof ApiBrandsBrandIdRoute
    }
    '/api/brands/$brandId/materials': {
      id: '/api/brands/$brandId/materials'
      path: '/materials'
      fullPath: '/api/brands/$brandId/materials'
      preLoaderRoute: typeof ApiBrandsBrandIdMaterialsRouteImport
      parentRoute: typeof ApiBrandsBrandIdRoute
    }
    '/api/brands/$brandId/counts': {
      id: '/api/brands/$brandId/counts'
      path: '/counts'
      fullPath: '/api/brands/$brandId/counts'
      preLoaderRoute: typeof ApiBrandsBrandIdCountsRouteImport
      parentRoute: typeof ApiBrandsBrandIdRoute
    }
    '/api/brands/$brandId/packages/new': {
      id: '/api/brands/$brandId/packages/new'
      path: '/new'
      fullPath: '/api/brands/$brandId/packages/new'
      preLoaderRoute: typeof ApiBrandsBrandIdPackagesNewRouteImport
      parentRoute: typeof ApiBrandsBrandIdPackagesRoute
    }
    '/api/brands/$brandId/packages/$packageId': {
      id: '/api/brands/$brandId/packages/$packageId'
      path: '/$packageId'
      fullPath: '/api/brands/$brandId/packages/$packageId'
      preLoaderRoute: typeof ApiBrandsBrandIdPackagesPackageIdRouteImport
      parentRoute: typeof ApiBrandsBrandIdPackagesRoute
    }
    '/api/brands/$brandId/materials/new': {
      id: '/api/brands/$brandId/materials/new'
      path: '/new'
      fullPath: '/api/brands/$brandId/materials/new'
      preLoaderRoute: typeof ApiBrandsBrandIdMaterialsNewRouteImport
      parentRoute: typeof ApiBrandsBrandIdMaterialsRoute
    }
    '/api/brands/$brandId/materials/$materialId': {
      id: '/api/brands/$brandId/materials/$materialId'
      path: '/$materialId'
      fullPath: '/api/brands/$brandId/materials/$materialId'
      preLoaderRoute: typeof ApiBrandsBrandIdMaterialsMaterialIdRouteImport
      parentRoute: typeof ApiBrandsBrandIdMaterialsRoute
    }
  }
}

interface AccessoriesRouteChildren {
  AccessoriesIdRoute: typeof AccessoriesIdRoute
}

const AccessoriesRouteChildren: AccessoriesRouteChildren = {
  AccessoriesIdRoute: AccessoriesIdRoute,
}

const AccessoriesRouteWithChildren = AccessoriesRoute._addFileChildren(
  AccessoriesRouteChildren,
)

interface BrandsBrandIdRouteChildren {
  BrandsBrandIdMaterialsMaterialIdRoute: typeof BrandsBrandIdMaterialsMaterialIdRoute
}

const BrandsBrandIdRouteChildren: BrandsBrandIdRouteChildren = {
  BrandsBrandIdMaterialsMaterialIdRoute: BrandsBrandIdMaterialsMaterialIdRoute,
}

const BrandsBrandIdRouteWithChildren = BrandsBrandIdRoute._addFileChildren(
  BrandsBrandIdRouteChildren,
)

interface BrandsRouteChildren {
  BrandsBrandIdRoute: typeof BrandsBrandIdRouteWithChildren
  BrandsIndexRoute: typeof BrandsIndexRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsBrandIdRoute: BrandsBrandIdRouteWithChildren,
  BrandsIndexRoute: BrandsIndexRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

interface ContainersRouteChildren {
  ContainersIdRoute: typeof ContainersIdRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
}

const ContainersRouteChildren: ContainersRouteChildren = {
  ContainersIdRoute: ContainersIdRoute,
  ContainersIndexRoute: ContainersIndexRoute,
}

const ContainersRouteWithChildren = ContainersRoute._addFileChildren(
  ContainersRouteChildren,
)

interface EnumTableRouteChildren {
  EnumTableIdRoute: typeof EnumTableIdRoute
}

const EnumTableRouteChildren: EnumTableRouteChildren = {
  EnumTableIdRoute: EnumTableIdRoute,
}

const EnumTableRouteWithChildren = EnumTableRoute._addFileChildren(
  EnumTableRouteChildren,
)

interface EnumRouteChildren {
  EnumTableRoute: typeof EnumTableRouteWithChildren
  EnumIndexRoute: typeof EnumIndexRoute
}

const EnumRouteChildren: EnumRouteChildren = {
  EnumTableRoute: EnumTableRouteWithChildren,
  EnumIndexRoute: EnumIndexRoute,
}

const EnumRouteWithChildren = EnumRoute._addFileChildren(EnumRouteChildren)

interface PrintSheetTypesRouteChildren {
  PrintSheetTypesSlugRoute: typeof PrintSheetTypesSlugRoute
  PrintSheetTypesTypeIdRoute: typeof PrintSheetTypesTypeIdRoute
}

const PrintSheetTypesRouteChildren: PrintSheetTypesRouteChildren = {
  PrintSheetTypesSlugRoute: PrintSheetTypesSlugRoute,
  PrintSheetTypesTypeIdRoute: PrintSheetTypesTypeIdRoute,
}

const PrintSheetTypesRouteWithChildren = PrintSheetTypesRoute._addFileChildren(
  PrintSheetTypesRouteChildren,
)

interface PrintersRouteChildren {
  PrintersIdRoute: typeof PrintersIdRoute
}

const PrintersRouteChildren: PrintersRouteChildren = {
  PrintersIdRoute: PrintersIdRoute,
}

const PrintersRouteWithChildren = PrintersRoute._addFileChildren(
  PrintersRouteChildren,
)

interface ApiBrandsBrandIdMaterialsRouteChildren {
  ApiBrandsBrandIdMaterialsMaterialIdRoute: typeof ApiBrandsBrandIdMaterialsMaterialIdRoute
  ApiBrandsBrandIdMaterialsNewRoute: typeof ApiBrandsBrandIdMaterialsNewRoute
}

const ApiBrandsBrandIdMaterialsRouteChildren: ApiBrandsBrandIdMaterialsRouteChildren =
  {
    ApiBrandsBrandIdMaterialsMaterialIdRoute:
      ApiBrandsBrandIdMaterialsMaterialIdRoute,
    ApiBrandsBrandIdMaterialsNewRoute: ApiBrandsBrandIdMaterialsNewRoute,
  }

const ApiBrandsBrandIdMaterialsRouteWithChildren =
  ApiBrandsBrandIdMaterialsRoute._addFileChildren(
    ApiBrandsBrandIdMaterialsRouteChildren,
  )

interface ApiBrandsBrandIdPackagesRouteChildren {
  ApiBrandsBrandIdPackagesPackageIdRoute: typeof ApiBrandsBrandIdPackagesPackageIdRoute
  ApiBrandsBrandIdPackagesNewRoute: typeof ApiBrandsBrandIdPackagesNewRoute
}

const ApiBrandsBrandIdPackagesRouteChildren: ApiBrandsBrandIdPackagesRouteChildren =
  {
    ApiBrandsBrandIdPackagesPackageIdRoute:
      ApiBrandsBrandIdPackagesPackageIdRoute,
    ApiBrandsBrandIdPackagesNewRoute: ApiBrandsBrandIdPackagesNewRoute,
  }

const ApiBrandsBrandIdPackagesRouteWithChildren =
  ApiBrandsBrandIdPackagesRoute._addFileChildren(
    ApiBrandsBrandIdPackagesRouteChildren,
  )

interface ApiBrandsBrandIdRouteChildren {
  ApiBrandsBrandIdCountsRoute: typeof ApiBrandsBrandIdCountsRoute
  ApiBrandsBrandIdMaterialsRoute: typeof ApiBrandsBrandIdMaterialsRouteWithChildren
  ApiBrandsBrandIdPackagesRoute: typeof ApiBrandsBrandIdPackagesRouteWithChildren
}

const ApiBrandsBrandIdRouteChildren: ApiBrandsBrandIdRouteChildren = {
  ApiBrandsBrandIdCountsRoute: ApiBrandsBrandIdCountsRoute,
  ApiBrandsBrandIdMaterialsRoute: ApiBrandsBrandIdMaterialsRouteWithChildren,
  ApiBrandsBrandIdPackagesRoute: ApiBrandsBrandIdPackagesRouteWithChildren,
}

const ApiBrandsBrandIdRouteWithChildren =
  ApiBrandsBrandIdRoute._addFileChildren(ApiBrandsBrandIdRouteChildren)

interface ApiBrandsRouteChildren {
  ApiBrandsBrandIdRoute: typeof ApiBrandsBrandIdRouteWithChildren
  ApiBrandsBasicRoute: typeof ApiBrandsBasicRoute
}

const ApiBrandsRouteChildren: ApiBrandsRouteChildren = {
  ApiBrandsBrandIdRoute: ApiBrandsBrandIdRouteWithChildren,
  ApiBrandsBasicRoute: ApiBrandsBasicRoute,
}

const ApiBrandsRouteWithChildren = ApiBrandsRoute._addFileChildren(
  ApiBrandsRouteChildren,
)

interface ApiContainersRouteChildren {
  ApiContainersContainerIdRoute: typeof ApiContainersContainerIdRoute
  ApiContainersIdRoute: typeof ApiContainersIdRoute
}

const ApiContainersRouteChildren: ApiContainersRouteChildren = {
  ApiContainersContainerIdRoute: ApiContainersContainerIdRoute,
  ApiContainersIdRoute: ApiContainersIdRoute,
}

const ApiContainersRouteWithChildren = ApiContainersRoute._addFileChildren(
  ApiContainersRouteChildren,
)

interface ApiEnumTableRouteChildren {
  ApiEnumTableIdRoute: typeof ApiEnumTableIdRoute
}

const ApiEnumTableRouteChildren: ApiEnumTableRouteChildren = {
  ApiEnumTableIdRoute: ApiEnumTableIdRoute,
}

const ApiEnumTableRouteWithChildren = ApiEnumTableRoute._addFileChildren(
  ApiEnumTableRouteChildren,
)

interface ApiEnumRouteChildren {
  ApiEnumTableRoute: typeof ApiEnumTableRouteWithChildren
}

const ApiEnumRouteChildren: ApiEnumRouteChildren = {
  ApiEnumTableRoute: ApiEnumTableRouteWithChildren,
}

const ApiEnumRouteWithChildren =
  ApiEnumRoute._addFileChildren(ApiEnumRouteChildren)

interface ApiMaterialsRouteChildren {
  ApiMaterialsMaterialIdRoute: typeof ApiMaterialsMaterialIdRoute
}

const ApiMaterialsRouteChildren: ApiMaterialsRouteChildren = {
  ApiMaterialsMaterialIdRoute: ApiMaterialsMaterialIdRoute,
}

const ApiMaterialsRouteWithChildren = ApiMaterialsRoute._addFileChildren(
  ApiMaterialsRouteChildren,
)

interface ApiPrintSheetTypesRouteChildren {
  ApiPrintSheetTypesSlugRoute: typeof ApiPrintSheetTypesSlugRoute
  ApiPrintSheetTypesTypeIdRoute: typeof ApiPrintSheetTypesTypeIdRoute
}

const ApiPrintSheetTypesRouteChildren: ApiPrintSheetTypesRouteChildren = {
  ApiPrintSheetTypesSlugRoute: ApiPrintSheetTypesSlugRoute,
  ApiPrintSheetTypesTypeIdRoute: ApiPrintSheetTypesTypeIdRoute,
}

const ApiPrintSheetTypesRouteWithChildren =
  ApiPrintSheetTypesRoute._addFileChildren(ApiPrintSheetTypesRouteChildren)

interface DevicesAccessoriesRouteChildren {
  DevicesAccessoriesIdRoute: typeof DevicesAccessoriesIdRoute
}

const DevicesAccessoriesRouteChildren: DevicesAccessoriesRouteChildren = {
  DevicesAccessoriesIdRoute: DevicesAccessoriesIdRoute,
}

const DevicesAccessoriesRouteWithChildren =
  DevicesAccessoriesRoute._addFileChildren(DevicesAccessoriesRouteChildren)

interface DevicesPrintersRouteChildren {
  DevicesPrintersIdRoute: typeof DevicesPrintersIdRoute
  DevicesPrintersPrinterIdRoute: typeof DevicesPrintersPrinterIdRoute
}

const DevicesPrintersRouteChildren: DevicesPrintersRouteChildren = {
  DevicesPrintersIdRoute: DevicesPrintersIdRoute,
  DevicesPrintersPrinterIdRoute: DevicesPrintersPrinterIdRoute,
}

const DevicesPrintersRouteWithChildren = DevicesPrintersRoute._addFileChildren(
  DevicesPrintersRouteChildren,
)

interface ApiDevicesAccessoriesRouteChildren {
  ApiDevicesAccessoriesAccessoryIdRoute: typeof ApiDevicesAccessoriesAccessoryIdRoute
  ApiDevicesAccessoriesIdRoute: typeof ApiDevicesAccessoriesIdRoute
}

const ApiDevicesAccessoriesRouteChildren: ApiDevicesAccessoriesRouteChildren = {
  ApiDevicesAccessoriesAccessoryIdRoute: ApiDevicesAccessoriesAccessoryIdRoute,
  ApiDevicesAccessoriesIdRoute: ApiDevicesAccessoriesIdRoute,
}

const ApiDevicesAccessoriesRouteWithChildren =
  ApiDevicesAccessoriesRoute._addFileChildren(
    ApiDevicesAccessoriesRouteChildren,
  )

interface ApiDevicesPrintersRouteChildren {
  ApiDevicesPrintersIdRoute: typeof ApiDevicesPrintersIdRoute
  ApiDevicesPrintersPrinterIdRoute: typeof ApiDevicesPrintersPrinterIdRoute
}

const ApiDevicesPrintersRouteChildren: ApiDevicesPrintersRouteChildren = {
  ApiDevicesPrintersIdRoute: ApiDevicesPrintersIdRoute,
  ApiDevicesPrintersPrinterIdRoute: ApiDevicesPrintersPrinterIdRoute,
}

const ApiDevicesPrintersRouteWithChildren =
  ApiDevicesPrintersRoute._addFileChildren(ApiDevicesPrintersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRouteWithChildren,
  BrandsRoute: BrandsRouteWithChildren,
  ContainersRoute: ContainersRouteWithChildren,
  EnumRoute: EnumRouteWithChildren,
  PrintSheetTypesRoute: PrintSheetTypesRouteWithChildren,
  PrintersRoute: PrintersRouteWithChildren,
  ApiBrandsRoute: ApiBrandsRouteWithChildren,
  ApiContainersRoute: ApiContainersRouteWithChildren,
  ApiEnumRoute: ApiEnumRouteWithChildren,
  ApiMaterialsRoute: ApiMaterialsRouteWithChildren,
  ApiPackagesRoute: ApiPackagesRoute,
  ApiPrintSheetTypesRoute: ApiPrintSheetTypesRouteWithChildren,
  ApiSchemaRoute: ApiSchemaRoute,
  DevicesAccessoriesRoute: DevicesAccessoriesRouteWithChildren,
  DevicesPrintersRoute: DevicesPrintersRouteWithChildren,
  MaterialsMaterialIdRoute: MaterialsMaterialIdRoute,
  ApiDevicesAccessoriesRoute: ApiDevicesAccessoriesRouteWithChildren,
  ApiDevicesPrintersRoute: ApiDevicesPrintersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
