/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-schema-metadata.ts
 * Generated at: 2026-01-08T23:28:45.203Z
 *
 * This file provides explicit field mappings for enums and entities,
 * eliminating guessing patterns like `item.slug || item.key || item.name`.
 */

export interface EnumMetadata {
  /** The field used as the stored value (e.g., 'name', 'abbreviation', 'code') */
  valueField: string;
  /** The field used for display labels (e.g., 'display_name', 'name') */
  labelField: string;
  entity: string;
}

export interface RelationMetadata {
  /** Whether this is an array relation */
  isArray?: boolean;
  /** The target entity route in app */
  route?: string;
}

/**
 * Field-to-enum mapping for known enum fields with explicit value and label fields.
 */
export const FIELD_ENUM_MAP: Record<string, EnumMetadata> = {
  type: {
    entity: 'material_types',
    valueField: 'abbreviation',
    labelField: 'name',
  },
  tags: {
    entity: 'material_tags',
    valueField: 'name',
    labelField: 'display_name',
  },
  certifications: {
    entity: 'material_certifications',
    valueField: 'name',
    labelField: 'display_name',
  },
  countries_of_origin: {
    entity: 'countries',
    valueField: 'key',
    labelField: 'name',
  },
  category: {
    entity: 'material_tag_categories',
    valueField: 'name',
    labelField: 'display_name',
  },
  photo_type: {
    entity: 'material_photo_types',
    valueField: 'name',
    labelField: 'name',
  },
  brand_link_pattern_types: {
    entity: 'brand_link_pattern_types',
    valueField: 'name',
    labelField: 'name',
  },
};

/*
 * Field-to-relation mapping for known relation fields.
 */
export const FIELD_RELATION_MAP: Record<
  string,
  RelationMetadata & EnumMetadata
> = {
  brand: {
    entity: 'brands',
    valueField: 'slug',
    labelField: 'name',
    route: '/brands/$brandId',
  },
  material: {
    entity: 'materials',
    valueField: 'slug',
    labelField: 'name',
    route: '/brands/$brandId',
  },
  container: {
    entity: 'containers',
    valueField: 'slug',
    labelField: 'name',
    route: `/containers/$containerId`,
  },
  package: {
    entity: 'packages',
    valueField: 'slug',
    labelField: 'name',
    route: '/brands/$brandId',
  },
};
